# Generated by Django 3.2.5 on 2021-11-18 04:44

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(blank=True, max_length=100, null=True)),
                ('evaluation', models.CharField(choices=[('excellent', '☆'), ('good', '◎'), ('normal', '〇'), ('bad', '×')], default='good', max_length=10)),
                ('place', models.CharField(choices=[('home', 'Home'), ('zym', 'Zym'), ('others', 'Others')], default='home', max_length=10, verbose_name='Place')),
                ('created_at', models.DateField(default=datetime.datetime(2021, 11, 18, 4, 44, 39, 691590, tzinfo=utc), verbose_name='Date')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_type', models.CharField(choices=[('bench_press', 'ベンチプレス'), ('incline_bench_press', 'インクラインベンチプレス'), ('dumbbell_press', 'ダンベルプレス'), ('shoulder_press', 'ショルダープレス'), ('lat_pull_down', 'ラットプルダウン'), ('chinning', 'チンニング'), ('push-up', '腕立て'), ('over_head_press', 'トライセプスエクステンション'), ('side_rise', 'サイドレイズ'), ('arm_curl', 'アームカール'), ('dips', 'ディップス'), ('kick_back', 'キックバック'), ('arm_variations', '上腕総合'), ('something_new', '新種目')], max_length=40)),
                ('weight', models.PositiveIntegerField(default=70, verbose_name='Weight[Kg]')),
                ('set1', models.PositiveIntegerField(default=10)),
                ('set2', models.PositiveIntegerField(blank=True, default=9, null=True)),
                ('set3', models.PositiveIntegerField(blank=True, default=8, null=True)),
                ('id_training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_training', to='api.training')),
            ],
        ),
    ]
