# Generated by Django 3.2.5 on 2021-10-18 00:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_training_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='body_weight_10',
        ),
        migrations.AlterField(
            model_name='content',
            name='training_type',
            field=models.CharField(choices=[('push-up_normal', '腕立て(normal)'), ('push-up_wide', '腕立て(wide)'), ('bench_press', 'ベンチプレス'), ('arm_variations', '上腕総合'), ('chinning', 'チンニング'), ('shoulder_press', 'ショルダープレス'), ('over_head_press', 'オーバーヘッドプレス'), ('side_rise', 'サイドレイズ'), ('arm_curl', 'アームカール'), ('kick_back', 'キックバック'), ('something_new', '新種目')], max_length=40),
        ),
        migrations.AlterField(
            model_name='content',
            name='weight',
            field=models.PositiveIntegerField(default=70, verbose_name='Weight[Kg]'),
        ),
        migrations.AlterField(
            model_name='training',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 0, 24, 14, 553383, tzinfo=utc), verbose_name='Date'),
        ),
    ]
