# Generated by Django 3.2.5 on 2021-10-18 11:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211018_0924'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='created_at',
            new_name='id_training',
        ),
        migrations.AlterField(
            model_name='training',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2021, 10, 18, 11, 48, 23, 347024, tzinfo=utc), verbose_name='Date'),
        ),
    ]
