# Generated by Django 3.2.5 on 2021-10-26 01:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20211018_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2021, 10, 26, 1, 3, 53, 626755, tzinfo=utc), verbose_name='Date'),
        ),
    ]
