# Generated by Django 3.2.5 on 2021-10-26 02:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_training_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='training_type',
            field=models.CharField(choices=[('bench_press', 'ベンチプレス'), ('incline_bench_press', 'インクラインベンチプレス'), ('shoulder_press', 'ショルダープレス'), ('chinning', 'チンニング'), ('push-up', '腕立て'), ('over_head_press', 'オーバーヘッドプレス'), ('side_rise', 'サイドレイズ'), ('arm_curl', 'アームカール'), ('kick_back', 'キックバック'), ('arm_variations', '上腕総合'), ('something_new', '新種目')], max_length=40),
        ),
        migrations.AlterField(
            model_name='training',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2021, 10, 26, 2, 24, 43, 811683, tzinfo=utc), verbose_name='Date'),
        ),
    ]
