# Generated by Django 3.2.5 on 2021-11-06 02:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20211106_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2021, 11, 6, 2, 6, 25, 601267, tzinfo=utc), verbose_name='Date'),
        ),
    ]
