# Generated by Django 3.2.5 on 2021-11-16 02:56

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_training_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='content',
            name='id_training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_training', to='api.training'),
        ),
        migrations.AlterField(
            model_name='content',
            name='training_type',
            field=models.CharField(choices=[('bench_press', 'ベンチプレス'), ('incline_bench_press', 'インクラインベンチプレス'), ('dumbbell_press', 'ダンベルプレス'), ('shoulder_press', 'ショルダープレス'), ('lat_pull_down', 'ラットプルダウン'), ('chinning', 'チンニング'), ('push-up', '腕立て'), ('over_head_press', 'オーバーヘッドプレス'), ('side_rise', 'サイドレイズ'), ('arm_curl', 'アームカール'), ('dips', 'ディップス'), ('kick_back', 'キックバック'), ('arm_variations', '上腕総合'), ('something_new', '新種目')], max_length=40),
        ),
        migrations.AlterField(
            model_name='training',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2021, 11, 16, 2, 56, 35, 515956, tzinfo=utc), verbose_name='Date'),
        ),
    ]
