# Generated by Django 3.2.5 on 2021-11-16 01:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20211115_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 11, 16, 1, 36, 16, 246226, tzinfo=utc), null=True, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='content',
            name='total_weight',
            field=models.PositiveIntegerField(default='(<django.db.models.fields.PositiveIntegerField> * (<django.db.models.fields.PositiveIntegerField> + <django.db.models.fields.PositiveIntegerField> + <django.db.models.fields.PositiveIntegerField>))'),
        ),
        migrations.AlterField(
            model_name='training',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2021, 11, 16, 1, 36, 16, 246226, tzinfo=utc), verbose_name='Date'),
        ),
    ]
