# Generated by Django 3.2.5 on 2021-11-16 01:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20211116_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 11, 16, 1, 40, 36, 575903, tzinfo=utc), null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='content',
            name='total_weight',
            field=models.CharField(default='<django.db.models.fields.PositiveIntegerField> * (<django.db.models.fields.PositiveIntegerField> + <django.db.models.fields.PositiveIntegerField> + <django.db.models.fields.PositiveIntegerField>)', max_length=40),
        ),
        migrations.AlterField(
            model_name='training',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2021, 11, 16, 1, 40, 36, 575903, tzinfo=utc), verbose_name='Date'),
        ),
    ]
