# Generated by Django 3.2.5 on 2021-11-20 06:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Memo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('memo', models.CharField(max_length=300)),
                ('category', models.CharField(choices=[('training', 'トレーニング'), ('habit', '習慣'), ('future', '将来'), ('study', '勉強'), ('other', 'その他')], max_length=30)),
                ('created_at', models.DateField(default=datetime.datetime(2021, 11, 20, 6, 44, 5, 848359, tzinfo=utc))),
            ],
        ),
    ]
