# Generated by Django 3.2.5 on 2021-11-20 06:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('memo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memo',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2021, 11, 20, 6, 44, 55, 747986, tzinfo=utc)),
        ),
    ]
